### PR TITLE
Handle nested section-creating elements in SectionParser

### LINKED ISSUE #648: Pasting HTML - wrappers cause unexpected results
I've searched as best I could but can't figure out if this behaviour is a bug or expected.

This is reproducible for me both by copy-pasting into the [demo editor](https://bustle.github.io/mobiledoc-kit/demo/) and programatically using the DomParser and Mobiledoc Renderer.

Paste: `<p>Hello</p><p>World</p>`

Resulting Mobiledoc.sections:

`
[ [ 1, 'p', [ [ 0, [], 0, 'Hello' ] ] ],
  [ 1, 'p', [ [ 0, [], 0, 'World' ] ] ] ]
`

Paste: `<div><p>Hello</p><p>World</p></div>`

Resulting Mobiledoc.sections:

`[ [ 1, 'p', [ [ 0, [], 0, 'HelloWorld' ] ] ] ]`

I'll try to add a minimal test example to show this in action, but I wanted to raise the issue in advance to check if this is expected behaviour?

If not, I'd be very happy to work towards a fix but might need a little pointer in the right direction. I feel like https://github.com/bustle/mobiledoc-kit/commit/9b4231ebc1fa5740c4f4cc7b768ed55d9cbb6ec9 might be related?

### PR DESCRIPTION
**Pull request by kevinansfield**
closes #654, closes #648 

Updates the `SectionParser` to properly close the current section and start a new one if a "section-creating" element is encountered whilst walking the node tree. This was already being handled for sections added via parser plugins but nested elements were overwriting the current section state rather than creating new sections where necessary.

Also removes the `_parseListElements` function in favour of handling list elements through `parseNode` and `_closeCurrentSection` which allows for extracting nested lists into a single top-level  list section.

Behaviour changes:
- section content with a wrapper element is no longer smushedtogether
- nested lists are treated as a single list (previous behaviour was for all text content of the nested list to be smushedtogether into a single list item)
- list items containing structural sections are parsed as structural sections rather than list items (previous behaviour was for the text content of each section in the `<li>` to be smushedtogether)
  - one exception is list elements containing a single paragraph (`<ul><li><p>content</p></li></ul>`) which will retain the list structure

### CODE REVIEW

File: src/js/parsers/section.js [hunk 1]
```diff
@@ -148,6 +154,28 @@ class SectionParser {
       return;
     }
 
+    // handle closing the current section and starting a new one if we hit a
+    // new-section-creating element. Skip if we're currently in a list-item
+    // section so that nested lists can be combined
```
Comment (mixonic) [inline src/js/parsers/section.js]: @kevinansfield is there a test case for this `Skip if we're currently in a list-item section so that nested lists can be combined`? I don't think so, can it be added?

Comment (kevinansfield) [reply src/js/parsers/section.js]: @mixonic you're absolutely right, nested grouping wasn't handled at all! I've removed the comment and added a commit with tests of the existing list parsing behaviour to show that it hasn't changed.

I'll push another commit shortly which has a fix for nested lists too but it required some further modification of the section parser. It also has some behaviour changes which _may_ be breaking so I'll comment on those separately.

File: src/js/parsers/section.js [hunk 2]
```diff
@@ -80,31 +80,16 @@ class SectionParser {
...
 
     this._closeCurrentSection();
 
     return this.sections;
   }
 
-  parseListItems(childNodes) {
-    let { state } = this;
-    forEach(childNodes, el => {
-      let parsed = new this.constructor(this.builder).parse(el);
```
Comment (kevinansfield) [inline src/js/parsers/section.js]: Creating a new SectionParser instance was the main reason for getting rid of this code. To be able to detect nested lists we need access to the current state which is not available in the new instance.

File: src/js/parsers/section.js [hunk 3]
```diff
@@ -155,29 +140,44 @@ class SectionParser {
...
+      let isNestedListSection = contains(VALID_LIST_SECTION_TAGNAMES, tagName)
+        && this.state.section.isListItem;
+
+      if (
+        contains(VALID_MARKUP_SECTION_TAGNAMES, tagName) ||
+        (contains(VALID_LIST_SECTION_TAGNAMES, tagName) && !isNestedListSection) ||
+        contains(VALID_LIST_ITEM_TAGNAMES, tagName)
+      ) {
+        // don't break out of the list for list items that contain a single <p>.
+        // deals with typical case of <li><p>Text</p></li><li><p>Text</p></li>
```
Comment (kevinansfield) [inline src/js/parsers/section.js]: I added this because I've seen other editors and markdown parsers create this type of structure so I figured it would be good to add specific handling. Otherwise the new behaviour would end up dropping the list altogether, instead creating paragraph sections in place of list sections.

File: tests/unit/parsers/section-test.js [hunk 4]
```diff
@@ -199,12 +199,14 @@ test("#parse handles multiple paragraphs in list item", assert => {
   parser = new SectionParser(builder);
   let sections = parser.parse(element);
 
-  assert.equal(sections.length, 1, "single list section");
+  assert.equal(sections.length, 2, '2 sections');
```
Comment (kevinansfield) [inline tests/unit/parsers/section-test.js]: This is the behaviour change which may need some thought. The previous/current behaviour smushes the text content of all elements in the `<li>` together which isn't ideal but it does preserve the overall "list" structure, the new behaviour gives preference to the nested content which preserves document structure such as headings and paragraphs but removes the list.

File: src/js/parsers/section.js [hunk 5]
```diff
@@ -80,36 +80,27 @@ class SectionParser {
...
-  }
-
   runPlugins(node) {
     let isNodeFinished = false;
     let env = {
       addSection: (section) => {
-        this._closeCurrentSection();
+        // avoid creating empty paragraphs due to wrapper elements around
+        // parser-plugin-handled elements
+        if (this.state.section.isMarkerable && !this.state.text) {
```
Comment (kevinansfield) [inline src/js/parsers/section.js]: This pattern is repeated a couple of times, I wonder if it would make more sense to move it to `_closeCurrentSection` if we're OK with not copying blank markup sections from the source html?

File: src/js/parsers/section.js [hunk 6]
```diff
@@ -204,7 +238,18 @@ class SectionParser {
       this._createMarker();
     }
 
-    sections.push(state.section);
+    // push listItems onto the listSection or add a new section
+    if (state.section.isListItem && lastSection && lastSection.isListSection) {
+      lastSection.items.append(state.section);
```
Comment (kevinansfield) [inline src/js/parsers/section.js]: Note to self - add test to ensure consecutive `<ul>`'s do not get merged together.

File: src/js/parsers/section.js (hunk 5 above)
Comment (kevinansfield) [reply src/js/parsers/section.js]: > OK with not copying blank markup sections from the source html

To clarify this, the current behaviour with this PR is that blank markup sections are preserved. Eg: `<p>One</p><p></p><p>Two</p>` will result in three markup sections with the middle one being blank.

If we move the duplicated empty-section-removal logic to `_closeCurrentSection` then all blank markup sections would be removed.

Comment (kevinansfield) [reply src/js/parsers/section.js]: Scratch that - I was apparently mis-remembering behaviour, empty markup sections are ignored in both the `dom` and `section` parser. I'll add tests for such and resolve this

File: src/js/parsers/section.js (hunk 6 above)
Comment (kevinansfield) [reply src/js/parsers/section.js]: Added test + fix

**Comment by kevinansfield** [comment]
@mixonic updated to resolve requested changes and improved the behaviour of nested list handling, another 👀 and sanity check on the behaviour would be great when you have a moment 😄

File: src/js/parsers/section.js (hunk 3 above)
Comment (mixonic) [reply src/js/parsers/section.js]: @kevinansfield As far as I recall the section parser should only be parsing DOM we create or introduced by `contexteditable` interactions. For example paste events and importing HTML are handled via the DOM parser.

So the implication here is that browsers may insert `p` tags inside lists as the user interacts. Is that what you've seen?

Comment (kevinansfield) [reply src/js/parsers/section.js]: The DOM parser only grabs top-level elements and relies on the section parser to deal with all the nested elements, in this case the `LI` and `P` are always nested elements as they're inside a `UL`. The changes are primarily to do with handling pastes and using the parsers externally for html->mobiledoc.

Comment (mixonic) [reply src/js/parsers/section.js]: Yeah, as implemented here:

https://github.com/bustle/mobiledoc-kit/blob/28a746d694e08c7cfc426a4e71a8667b845a1a4d/src/js/parsers/dom.js#L140

You are correct. I feel like I should have caught this earlier, but if these are explicitly corrections to the paste parsing then we should implement them as corrections in the DOM parser before it passes content to the section parser. The section parser (in theory) should only be concerned with contexteditable-type inputs, not with any plausible HTML input from a paste. The latter is basically an unbounded set of concerns, and it is nice to keep them out of the editor parser.

File: tests/unit/parsers/section-test.js (hunk 4 above)
Comment (mixonic) [reply tests/unit/parsers/section-test.js]: We discussed this on Slack. When the DOM inside a `<li>` is trivial as in this test example you might want the smushing behavior, but as soon as there is arbitrarily complex content in the list item (many paragraphs, images, etc) considering this content as a candidate for top level sections is better behavior.

**Comment by mixonic** [comment]
I'm a go on these changes. @kevinansfield has a test failure he just discovered as we went over this, so we should wait on his work to proceed with merge.

**Comment by kevinansfield** [comment]
> @kevinansfield has a test failure he just discovered as we went over this, so we should wait on his work to proceed with merge.

Additional tests for the discovered error and associated fixes have been added 😄

**Comment by sdhull** [comment]
Thank you @kevinansfield!!  🎉 🎉
